<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="TPSamordningVarslingWSEXP_TPSamordningVarslingHttp_Service" 
targetNamespace="http://nav.no/elsam/tpsamordningvarsling/V1_0/Binding" 
xmlns:Port_0="http://nav.no/elsam/tpsamordningvarsling/V1_0" 
xmlns:bons1="http://nav.no/elsam/tpsamordningvarsling/V1_0/Binding" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl1="http://nav.no/elsam/tpsamordningvarsling/V1_0">
    <wsdl:import
    	namespace="http://nav.no/elsam/tpsamordningvarsling/V1_0"
    	location="../inf/TPSamordningVarsling.wsdl">
    </wsdl:import>
    <wsdl:binding
    	name="TPSamordningVarslingWSEXP_TPSamordningVarslingHttpBinding"
    	type="Port_0:TPSamordningVarsling">
    	<soap:binding style="document"
    		transport="http://schemas.xmlsoap.org/soap/http" />
    	<wsdl:operation name="varsleVedtakNAV">
    		<soap:operation soapAction="" />
    		<wsdl:input name="varsleVedtakNAVRequest">
    			<soap:body use="literal" />
    		</wsdl:input>
    		<wsdl:output name="varsleVedtakNAVResponse">
    			<soap:body use="literal" />
    		</wsdl:output>
    		<wsdl:fault name="faultGenerisk">
    			<soap:fault name="faultGenerisk" use="literal" />
    		</wsdl:fault>
    	</wsdl:operation>
    	<wsdl:operation name="varsleEndringTPYtelse">
    		<soap:operation soapAction="" />
    		<wsdl:input name="varsleEndringTPYtelseRequest">
    			<soap:body use="literal" />
    		</wsdl:input>
    		<wsdl:output name="varsleEndringTPYtelseResponse">
    			<soap:body use="literal" />
    		</wsdl:output>
    		<wsdl:fault name="faultGenerisk">
    			<soap:fault name="faultGenerisk" use="literal" />
    		</wsdl:fault>
    	</wsdl:operation>
    	<wsdl:operation name="varsleManglendeRefusjonskrav">
    		<soap:operation soapAction="" />
    		<wsdl:input name="varsleManglendeRefusjonskravRequest">
    			<soap:body use="literal" />
    		</wsdl:input>
    		<wsdl:output name="varsleManglendeRefusjonskravResponse">
    			<soap:body use="literal" />
    		</wsdl:output>
    		<wsdl:fault name="faultGenerisk">
    			<soap:fault name="faultGenerisk" use="literal" />
    		</wsdl:fault>
    	</wsdl:operation>
    	<wsdl:operation name="varsleEndringPersonalia">
    		<soap:operation soapAction="" />
    		<wsdl:input name="varsleEndringPersonaliaRequest">
    			<soap:body use="literal" />
    		</wsdl:input>
    		<wsdl:output name="varsleEndringPersonaliaResponse">
    			<soap:body use="literal" />
    		</wsdl:output>
    		<wsdl:fault name="faultGenerisk">
    			<soap:fault name="faultGenerisk" use="literal" />
    		</wsdl:fault>
    	</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="TPSamordningVarslingWSEXP_TPSamordningVarslingHttpService">
    <wsdl:port binding="bons1:TPSamordningVarslingWSEXP_TPSamordningVarslingHttpBinding" name="TPSamordningVarslingWSEXP_TPSamordningVarslingHttpPort">
      <soap:address location="https://partner-gw-t6.test.internsone.local:9443/nav-prod-elsam-tpsamordningvarslingWeb/sca/TPSamordningVarslingWSEXPV1_0"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>