<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
        name="Binding"
        targetNamespace="http://nav.no/samordning/tjenester/samordningsdata/v1/binding"
        xmlns:port="http://nav.no/samordning/tjenester/samordningsdata/v1"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:tns="http://nav.no/samordning/tjenester/samordningsdata/v1/binding">
  <wsdl:import namespace="http://nav.no/samordning/tjenester/samordningsdata/v1" location="Samordningsdata.wsdl">
    </wsdl:import>
  <wsdl:binding name="Samordningsdata_v1Binding" type="port:Samordningsdata_v1">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentSamordningsdata">
      <soap:operation soapAction="http://nav.no/samordning/tjenester/samordningsdata/v1/Samordningsdata_v1/hentSamordningsdataRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultTPForholdIkkeIverksatt">
        <soap:fault name="faultTPForholdIkkeIverksatt" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGenerisk">
        <soap:fault name="faultGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ping">
      <soap:operation soapAction="http://nav.no/samordning/tjenester/samordningsdata/v1/Samordningsdata_v1/pingRequest"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Samordningsdata_v1">
    <wsdl:port name="Samordningsdata_v1Port" binding="tns:Samordningsdata_v1Binding">
      <soap:address location="http://localhost:9080/samordningsdata"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
