<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="TPSamordningVarslingWSEXP_TPSamordningVarslingHttp_Service" 
targetNamespace="http://nav.no/samordning/tjenester/varslevedtak/v1/Binding"
xmlns:Port_0="http://nav.no/samordning/tjenester/varslevedtak/v1"
xmlns:bons1="http://nav.no/samordning/tjenester/varslevedtak/v1/Binding"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:import
    	namespace="http://nav.no/samordning/tjenester/varslevedtak/v1"
    	location="TPSamordningVarsling.wsdl">
    </wsdl:import>
    <wsdl:binding
    	name="TPSamordningVarsling_v1Binding"
    	type="Port_0:TPSamordningVarsling">
    	<soap:binding style="document"
    		transport="http://schemas.xmlsoap.org/soap/http" />
    	<wsdl:operation name="varsleVedtakNAV">
    		<soap:operation soapAction="" />
    		<wsdl:input name="varsleVedtakNAVRequest">
    			<soap:body use="literal" />
    		</wsdl:input>
    		<wsdl:output name="varsleVedtakNAVResponse">
    			<soap:body use="literal" />
    		</wsdl:output>
    		<wsdl:fault name="faultGenerisk">
    			<soap:fault name="faultGenerisk" use="literal" />
    		</wsdl:fault>
    	</wsdl:operation>
		<wsdl:operation name="ping">
			<soap:operation soapAction="http://nav.no/samordning/tjenester/vedlikeholdtpforhold/v1/Vedlikeholdtpforhold_v1/pingRequest"/>
			<wsdl:input>
				<soap:body parts="parameters" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="parameters" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="TPSamordningVarsling_v1">
    <wsdl:port binding="bons1:TPSamordningVarsling_v1Binding" name="TPSamordningVarsling_v1Port">
      <soap:address location="http://localhost:9080/tpsamordningvarsling"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>