name: Release to GitHub Package Registry

on:
  push:
    branches: master

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Build and release
      - name: Build
        run: mvn clean -B -V verify

      # Release
      - name: Set version
        run: |
          echo "$(git rev-parse --short HEAD)" > .version
          mvn versions:set -DnewVersion="$(cat .version)"
      - name: Release
        run: mvn -B -V -fn deploy -X -DskipTests=true -Dmaven.install.skip=true
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}