name: Release to GitHub Package Registry

on:
  push:
    branches: master

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Calculate revision
        id: revision
        shell: bash
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          echo "revision=$TIME-$COMMIT" >> $GITHUB_OUTPUT

      - name: Build
        run: mvn clean -B verify

      - name: Release
        run: mvn -B -Drevision="${REVISION}" -DskipTests=true source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVISION: ${{ steps.revision.outputs.revision }}
